inputConfig = {
  player_1 = {
      { action = 'UP', device = 'KEYBOARD', port = '1', key = 'W'},
      { action = 'DOWN', device = 'KEYBOARD', port = '1', key = 'S' },
      { action = 'LEFT', device = 'KEYBOARD', port = '1', key = 'A'},
      { action = 'RIGHT', device = 'KEYBOARD', port = '1', key = 'D'},
      { action = 'JUMP', device = 'KEYBOARD', port = '1', key = 'SPACE'},
      { action = 'FIRE', device = 'KEYBOARD', port = '1', key = 'SHIFT'},
      { action = 'USE', device = 'KEYBOARD', port = '1', key = 'E'},
      { action = 'WEAPON_RELOAD', device = 'KEYBOARD', port = '1', key = 'R'},
      { action = 'WEAPON_SELECT_NEXT', device = 'KEYBOARD', port = '1', key = 'C'},
      { action = 'WEAPON_SELECT_PREVIOUS', device = 'KEYBOARD', port = '1', key = 'Z'},
      { action = 'WEAPON_SELECT_1', device = 'KEYBOARD', port = '1', key = '1'},
      { action = 'WEAPON_SELECT_2', device = 'KEYBOARD', port = '1', key = '2'},
      { action = 'WEAPON_SELECT_3', device = 'KEYBOARD', port = '1', key = '3'}
  },
  player_2 = {
      { action = 'UP', device = 'KEYBOARD', port = '2', key = 'W'},
      { action = 'DOWN', device = 'KEYBOARD', port = '2', key = 'S' },
      { action = 'LEFT', device = 'KEYBOARD', port = '2', key = 'A'},
      { action = 'RIGHT', device = 'KEYBOARD', port = '2', key = 'D'},
      { action = 'JUMP', device = 'KEYBOARD', port = '2', key = 'SPACE'},
      { action = 'FIRE', device = 'KEYBOARD', port = '2', key = 'SHIFT'},
      { action = 'USE', device = 'KEYBOARD', port = '2', key = 'E'},
      { action = 'WEAPON_RELOAD', device = 'KEYBOARD', port = '2', key = 'R'},
      { action = 'WEAPON_SELECT_NEXT', device = 'KEYBOARD', port = '2', key = 'C'},
      { action = 'WEAPON_SELECT_PREVIOUS', device = 'KEYBOARD', port = '2', key = 'Z'},
      { action = 'WEAPON_SELECT_1', device = 'KEYBOARD', port = '2', key = '1'},
      { action = 'WEAPON_SELECT_2', device = 'KEYBOARD', port = '2', key = '2'},
      { action = 'WEAPON_SELECT_3', device = 'KEYBOARD', port = '2', key = '3'}
  },
  player_3 = {
      { action = 'UP', device = 'KEYBOARD', port = '3', key = 'W'},
      { action = 'DOWN', device = 'KEYBOARD', port = '3', key = 'S' },
      { action = 'LEFT', device = 'KEYBOARD', port = '3', key = 'A'},
      { action = 'RIGHT', device = 'KEYBOARD', port = '3', key = 'D'},
      { action = 'JUMP', device = 'KEYBOARD', port = '3', key = 'SPACE'},
      { action = 'FIRE', device = 'KEYBOARD', port = '3', key = 'SHIFT'},
      { action = 'USE', device = 'KEYBOARD', port = '3', key = 'E'},
      { action = 'WEAPON_RELOAD', device = 'KEYBOARD', port = '3', key = 'R'},
      { action = 'WEAPON_SELECT_NEXT', device = 'KEYBOARD', port = '3', key = 'C'},
      { action = 'WEAPON_SELECT_PREVIOUS', device = 'KEYBOARD', port = '3', key = 'Z'},
      { action = 'WEAPON_SELECT_1', device = 'KEYBOARD', port = '3', key = '1'},
      { action = 'WEAPON_SELECT_2', device = 'KEYBOARD', port = '3', key = '2'},
      { action = 'WEAPON_SELECT_3', device = 'KEYBOARD', port = '3', key = '3'}
  },
  player_4 = {
      { action = 'UP', device = 'KEYBOARD', port = '4', key = 'W'},
      { action = 'DOWN', device = 'KEYBOARD', port = '4', key = 'S' },
      { action = 'LEFT', device = 'KEYBOARD', port = '4', key = 'A'},
      { action = 'RIGHT', device = 'KEYBOARD', port = '4', key = 'D'},
      { action = 'JUMP', device = 'KEYBOARD', port = '4', key = 'SPACE'},
      { action = 'FIRE', device = 'KEYBOARD', port = '4', key = 'SHIFT'},
      { action = 'USE', device = 'KEYBOARD', port = '4', key = 'E'},
      { action = 'WEAPON_RELOAD', device = 'KEYBOARD', port = '4', key = 'R'},
      { action = 'WEAPON_SELECT_NEXT', device = 'KEYBOARD', port = '4', key = 'C'},
      { action = 'WEAPON_SELECT_PREVIOUS', device = 'KEYBOARD', port = '4', key = 'Z'},
      { action = 'WEAPON_SELECT_1', device = 'KEYBOARD', port = '4', key = '1'},
      { action = 'WEAPON_SELECT_2', device = 'KEYBOARD', port = '4', key = '2'},
      { action = 'WEAPON_SELECT_3', device = 'KEYBOARD', port = '4', key = '3'}
  }
}